/* ============================================================
   Oqra — preset-share decoder (client-side, no build, no network)
   ============================================================
   Ports PresetQRCodec (Packages/FilmBoCore/.../PresetQRCodec.swift)
   to the browser: paste an oqra.app/p/<payload> link (or the bare
   payload), and download a drop-in .fbp the app imports.

   Wire format (MSB-first bitstream), decode order:
     header 10b : version4 · layerCount-1 2 · hasCalK · hasRawBoost
                  · bypass · recoverHighlights
     global 52b : maskDensity7 dirInhibition7 baseTintWarmth8
                  scanExposure8 grainSoftness8 halation7 exposureEV7
     cond.      : calibrationK10? · rawBoost7? · localToneMap7 (v==3)
     layer×N 83b: sensitizerPeak9 sensitizerBw8 dyeHue9 dyePurity7
                  dmax9 fog8 hdToe8 hdGamma9 hdShoulder8 crystalSize8
     v4 grain   : flag+localToneMap(1+7?) flag+grainGain(1+7?)
                  flag+grainSharpness(1+7?)            (v>=4 only)
     name(v2-4) : len1 + UTF-8, byte-aligned        · CRC-16/CCITT-FALSE
   ============================================================ */
(function () {
  "use strict";

  var URL_MARK = "/p/";

  // ParameterRanges — must match ParameterRanges.swift exactly.
  var R = {
    maskDensity:   [0, 1],
    dirInhibition: [0, 1],
    baseTintWarmth:[-1, 1],
    scanExposure:  [-1, 1],
    grainSoftness: [0, 2.0],
    halation:      [0, 1],
    exposureEV:    [-3, 3],
    calibrationK:  [2500, 10000],
    rawBoost:      [0, 1],
    localToneMap:  [0, 1],
    sensitizerPeak:[380, 700],
    sensitizerBw:  [30, 200],
    dyeHue:        [0, 360],
    dyePurity:     [0, 1],
    dmax:          [0.05, 3.5],
    fog:           [0, 0.3],
    hdToe:         [0, 0.5],
    hdGamma:       [0.3, 3.0],
    hdShoulder:    [0, 0.5],
    crystalSize:   [0, 0.5],
    grainGain:     [0, 2],
    grainSharpness:[0, 1],
  };

  function extractPayload(input) {
    var s = (input || "").trim();
    var i = s.indexOf(URL_MARK);
    if (i !== -1) s = s.slice(i + URL_MARK.length);
    // tolerate a trailing slash / query / fragment
    s = s.split(/[/?#]/)[0];
    return s;
  }

  function base64urlDecode(s) {
    var t = s.replace(/-/g, "+").replace(/_/g, "/");
    while (t.length % 4 !== 0) t += "=";
    var bin = atob(t); // throws on invalid input
    var out = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }

  function crc16(bytes) {
    var crc = 0xffff;
    for (var i = 0; i < bytes.length; i++) {
      crc ^= (bytes[i] << 8) & 0xffff;
      for (var b = 0; b < 8; b++) {
        crc = (crc & 0x8000) ? ((crc << 1) ^ 0x1021) & 0xffff : (crc << 1) & 0xffff;
      }
    }
    return crc;
  }

  function BitReader(bytes) { this.bytes = bytes; this.pos = 0; }
  BitReader.prototype.read = function (count) {
    var v = 0;
    for (var i = 0; i < count; i++) {
      var byteIdx = this.pos >> 3;
      var bitIdx = 7 - (this.pos & 7);
      var bit = byteIdx < this.bytes.length ? (this.bytes[byteIdx] >> bitIdx) & 1 : 0;
      v = (v << 1) | bit;
      this.pos++;
    }
    return v >>> 0;
  };

  // dequant: lower + code/(2^bits - 1) * (upper - lower)   [range = [lo, hi]]
  function dq(code, range, bits) {
    var n = (1 << bits) - 1;
    return range[0] + (code / n) * (range[1] - range[0]);
  }

  function layerName(index, count) {
    if (count === 1) return "silver";
    var names = ["cyan", "magenta", "yellow"];
    return index < names.length ? names[index] : "layer " + (index + 1);
  }

  function uuid() {
    var c = (typeof globalThis !== "undefined" && globalThis.crypto) ? globalThis.crypto : null;
    if (c && c.randomUUID) return c.randomUUID();
    // RFC4122-ish fallback (id is regenerated by the app on import anyway)
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
      var r = (Math.random() * 16) | 0, v = c === "x" ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }

  // Decode a base64url payload (or full URL) -> { name, recipe }.
  // Throws Error("tooShort" | "badPayload" | "badCRC" | "unsupportedVersion: N").
  function decode(input) {
    var payload = extractPayload(input);
    if (!payload) throw new Error("badPayload");

    var all;
    try { all = base64urlDecode(payload); }
    catch (e) { throw new Error("badPayload"); }

    if (all.length < 3) throw new Error("tooShort");

    var body = all.subarray(0, all.length - 2);
    var crcGiven = ((all[all.length - 2] << 8) | all[all.length - 1]) & 0xffff;
    if (crc16(body) !== crcGiven) throw new Error("badCRC");

    var r = new BitReader(body);
    var version = r.read(4);
    if (version < 1 || version > 4) throw new Error("unsupportedVersion: " + version);

    var layerCount = r.read(2) + 1;
    var hasCalK = r.read(1) === 1;
    var hasRawBoost = r.read(1) === 1;
    var bypass = r.read(1) === 1;
    var recoverHighlights = r.read(1) === 1;

    var global = {
      maskDensity:   dq(r.read(7), R.maskDensity, 7),
      maskHue:       0, // deprecated, engine-pinned
      dirInhibition: dq(r.read(7), R.dirInhibition, 7),
      baseTintWarmth:dq(r.read(8), R.baseTintWarmth, 8),
      scanExposure:  dq(r.read(8), R.scanExposure, 8),
      grainSoftness: dq(r.read(8), R.grainSoftness, 8),
      halation:      dq(r.read(7), R.halation, 7),
      exposureEV:    dq(r.read(7), R.exposureEV, 7),
      bypass:        bypass,
      recoverHighlights: recoverHighlights,
    };
    // Conditionals — written in this exact order in encode.
    global.calibrationK = hasCalK ? dq(r.read(10), R.calibrationK, 10) : null;
    global.rawBoost = hasRawBoost ? dq(r.read(7), R.rawBoost, 7) : null;
    // v3 carries localToneMap inline here; v4 relocates it into the flagged
    // grain block after the layers (so the inline read is v3-only).
    global.localToneMapAmount = version === 3 ? dq(r.read(7), R.localToneMap, 7) : null;
    global.grainGain = null;
    global.grainSharpness = null;

    var layers = [];
    for (var i = 0; i < layerCount; i++) {
      layers.push({
        id: uuid(),                       // fresh; app re-mints on import
        name: layerName(i, layerCount),
        sensitizerPeak: dq(r.read(9), R.sensitizerPeak, 9),
        sensitizerBw:   dq(r.read(8), R.sensitizerBw, 8),
        dyeHue:         dq(r.read(9), R.dyeHue, 9),
        dyePurity:      dq(r.read(7), R.dyePurity, 7),
        dmax:           dq(r.read(9), R.dmax, 9),
        fog:            dq(r.read(8), R.fog, 8),
        hdToe:          dq(r.read(8), R.hdToe, 8),
        hdGamma:        dq(r.read(9), R.hdGamma, 9),
        hdShoulder:     dq(r.read(8), R.hdShoulder, 8),
        crystalSize:    dq(r.read(8), R.crystalSize, 8),
      });
    }

    // v4 grain block (after the layers): flagged optionals — relocated
    // localToneMap, grainGain, grainSharpness. Absent in v1/v2/v3.
    var v4HasLTM = false, v4HasGG = false, v4HasGS = false;
    if (version >= 4) {
      v4HasLTM = r.read(1) === 1;
      if (v4HasLTM) global.localToneMapAmount = dq(r.read(7), R.localToneMap, 7);
      v4HasGG = r.read(1) === 1;
      if (v4HasGG) global.grainGain = dq(r.read(7), R.grainGain, 7);
      v4HasGS = r.read(1) === 1;
      if (v4HasGS) global.grainSharpness = dq(r.read(7), R.grainSharpness, 7);
    }

    // Optional name block (v2/v3/v4), byte-aligned after the recipe bits.
    var name = null;
    if (version >= 2) {
      var recipeBits = 10 + 52 + (hasCalK ? 10 : 0) + (hasRawBoost ? 7 : 0) +
        (version === 3 ? 7 : 0) + 83 * layerCount +
        (version >= 4 ? (3 + (v4HasLTM ? 7 : 0) + (v4HasGG ? 7 : 0) + (v4HasGS ? 7 : 0)) : 0);
      var lenIdx = Math.ceil(recipeBits / 8);
      if (lenIdx < body.length) {
        var len = body[lenIdx];
        var start = lenIdx + 1;
        if (len > 0 && start + len <= body.length) {
          name = new TextDecoder().decode(body.subarray(start, start + len));
        }
      }
    }

    return { name: name, recipe: { format: "35 mm", global: global, layers: layers } };
  }

  // Build a sorted-keys, 2-space .fbp string, omitting AUTO (null) conditionals.
  function buildFbp(decoded) {
    var g = decoded.recipe.global;
    var globalOut = {
      baseTintWarmth: g.baseTintWarmth,
      bypass: g.bypass,
      dirInhibition: g.dirInhibition,
      exposureEV: g.exposureEV,
      grainSoftness: g.grainSoftness,
      halation: g.halation,
      maskDensity: g.maskDensity,
      maskHue: g.maskHue,
      recoverHighlights: g.recoverHighlights,
      scanExposure: g.scanExposure,
    };
    // Explicit null checks — 0.0 is a legal value and must NOT be dropped.
    if (g.calibrationK !== null) globalOut.calibrationK = g.calibrationK;
    if (g.rawBoost !== null) globalOut.rawBoost = g.rawBoost;
    if (g.localToneMapAmount !== null) globalOut.localToneMapAmount = g.localToneMapAmount;
    // v4 grain controls — Optional in the recipe; emit only when present so a
    // default-grain share stays byte-stable (matches the Swift encodeIfPresent).
    if (g.grainGain != null) globalOut.grainGain = g.grainGain;
    if (g.grainSharpness != null) globalOut.grainSharpness = g.grainSharpness;

    var envelope = {
      kind: "preset",
      name: decoded.name || "Shared Recipe",
      recipe: { format: decoded.recipe.format, global: globalOut, layers: decoded.recipe.layers },
      version: 2,
    };
    return JSON.stringify(envelope, sortKeys, 2);
  }

  function sortKeys(key, value) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      return Object.keys(value).sort().reduce(function (acc, k) { acc[k] = value[k]; return acc; }, {});
    }
    return value;
  }

  function safeFilename(name) {
    var base = (name || "Shared Recipe").trim().replace(/[^\w.\- ]+/g, "").replace(/\s+/g, "_");
    return (base || "recipe") + ".fbp";
  }

  function downloadFbp(decoded) {
    var blob = new Blob([buildFbp(decoded)], { type: "application/json" });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = safeFilename(decoded.name);
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
  }

  // ---- UI ----

  var ERR = {
    tooShort: "That code looks too short to be an Oqra recipe.",
    badPayload: "Couldn't read that — paste the full oqra.app/p/… link or the code after /p/.",
    badCRC: "This code is incomplete or corrupted — copy the whole link and try again.",
  };
  function errMessage(e) {
    var m = e && e.message ? e.message : String(e);
    if (m.indexOf("unsupportedVersion") === 0) return "This code is from a newer version of Oqra than this page supports.";
    return ERR[m] || "Couldn't decode that code.";
  }

  function num(v, digits) {
    return (Math.round(v * Math.pow(10, digits)) / Math.pow(10, digits)).toString();
  }

  function renderSpec(decoded, host) {
    var g = decoded.recipe.global;
    var rows = [
      ["Layers", String(decoded.recipe.layers.length)],
      ["Grain softness", num(g.grainSoftness, 2)],
      ["Halation", num(g.halation, 2)],
      ["Exposure", (g.exposureEV >= 0 ? "+" : "") + num(g.exposureEV, 2) + " EV"],
      ["Film balance", g.calibrationK !== null ? Math.round(g.calibrationK) + " K" : "AUTO"],
    ];
    decoded.recipe.layers.forEach(function (l) {
      rows.push([l.name + " · peak", Math.round(l.sensitizerPeak) + " nm"]);
    });

    var rowsHtml = rows.map(function (r) {
      return '<div class="recipe-spec__row"><span>' + r[0] + "</span><b>" + r[1] + "</b></div>";
    }).join("");

    host.innerHTML =
      '<div class="recipe-spec">' +
        '<div class="recipe-spec__head">' +
          '<div class="recipe-spec__name">' + escapeHtml(decoded.name || "Shared Recipe") + "</div>" +
          '<div class="recipe-spec__kind">Film recipe</div>' +
        "</div>" +
        '<div class="recipe-spec__rows">' + rowsHtml + "</div>" +
      "</div>";
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  function init() {
    var field = document.getElementById("codeField");
    var decodeBtn = document.getElementById("decodeBtn");
    var dlBtn = document.getElementById("downloadBtn");
    var status = document.getElementById("decodeStatus");
    var specHost = document.getElementById("recipeSpec");
    if (!field || !decodeBtn) return;

    var current = null; // last successfully decoded recipe

    function setStatus(msg, kind) {
      status.textContent = msg || "";
      status.className = "decoder__status" + (kind ? " is-" + kind : "");
    }
    function reset() { current = null; specHost.innerHTML = ""; if (dlBtn) dlBtn.hidden = true; }

    function run() {
      reset();
      var raw = field.value;
      if (!raw.trim()) { setStatus("Paste a code or link above.", ""); return; }
      try {
        current = decode(raw);
        renderSpec(current, specHost);
        if (dlBtn) dlBtn.hidden = false;
        setStatus("Recipe decoded — download the .fbp, then open it in Oqra.", "ok");
      } catch (e) {
        setStatus(errMessage(e), "error");
      }
    }

    decodeBtn.addEventListener("click", run);
    if (dlBtn) dlBtn.addEventListener("click", function () { if (current) downloadFbp(current); });

    // Auto-fill + auto-decode when the page is served for /p/<code>
    // (Cloudflare rewrites /p/<code> -> / , URL stays /p/<code>), then scroll
    // the decode section into view so the result is what the visitor sees.
    if (location.href.indexOf(URL_MARK) !== -1) {
      var p = extractPayload(location.href);
      if (p) {
        field.value = p;
        run();
        var sec = document.getElementById("decode");
        if (sec) sec.scrollIntoView({ behavior: "auto", block: "start" });
      }
    }
  }

  if (typeof document !== "undefined") {
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
    else init();
  }

  // Expose for a quick console / Node self-test.
  if (typeof window !== "undefined") window.OqraShare = { decode: decode, buildFbp: buildFbp };
  if (typeof module !== "undefined" && module.exports) module.exports = { decode: decode, buildFbp: buildFbp };
})();
